version: '3.9'

services: 
  arbiter:
    build: ./
    container_name: arbiter-ml
    restart: on-failure
    ports: 
      - "5555:5000"
    volumes:
      - ./:/code
    depends_on:
      - arbiter-db

  arbiter-db:
    image: mongo
    restart: on-failure
    container_name: mongo-arbiter
    ports: 
      - "27017"
    volumes: 
      - arbiter-vol:/data/db

volumes: 
  arbiter-db:
